// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlK_nUheMIgSG4Kr042C_wES2MsWIJtD0',
    appId: '1:966415306637:web:f9378f4b99876d4169b7c4',
    messagingSenderId: '966415306637',
    projectId: 'language-784a0',
    authDomain: 'language-784a0.firebaseapp.com',
    storageBucket: 'language-784a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmixNaVYAR7l4i5DEtcluw6D-uXOdlSt8',
    appId: '1:966415306637:android:e0c88d908436575969b7c4',
    messagingSenderId: '966415306637',
    projectId: 'language-784a0',
    storageBucket: 'language-784a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX4aqYG40sBbnLgPcWGT0ANyZZnJKhZu4',
    appId: '1:966415306637:ios:8394a12a170833ce69b7c4',
    messagingSenderId: '966415306637',
    projectId: 'language-784a0',
    storageBucket: 'language-784a0.appspot.com',
    iosBundleId: 'com.example.famousRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX4aqYG40sBbnLgPcWGT0ANyZZnJKhZu4',
    appId: '1:966415306637:ios:396aa12a9c8cac5269b7c4',
    messagingSenderId: '966415306637',
    projectId: 'language-784a0',
    storageBucket: 'language-784a0.appspot.com',
    iosBundleId: 'com.example.famousRestaurant.RunnerTests',
  );
}
