// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmjuzpzKPy8_cr6mvLyzO02L6aQSkQ8zc',
    appId: '1:454995657689:web:35ae7ee77698fa63f48fc8',
    messagingSenderId: '454995657689',
    projectId: 'restaurant-6652e',
    authDomain: 'restaurant-6652e.firebaseapp.com',
    databaseURL: 'https://restaurant-6652e-default-rtdb.firebaseio.com',
    storageBucket: 'restaurant-6652e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ATSquWJZ2s6CDgLEE9S4XXS6r2tHug4',
    appId: '1:454995657689:android:2071ed23f0b560b1f48fc8',
    messagingSenderId: '454995657689',
    projectId: 'restaurant-6652e',
    databaseURL: 'https://restaurant-6652e-default-rtdb.firebaseio.com',
    storageBucket: 'restaurant-6652e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-nALvU6tUyAnEtdQ--7hQ6kLaW5c1xbQ',
    appId: '1:454995657689:ios:7608ddeecbbe3047f48fc8',
    messagingSenderId: '454995657689',
    projectId: 'restaurant-6652e',
    databaseURL: 'https://restaurant-6652e-default-rtdb.firebaseio.com',
    storageBucket: 'restaurant-6652e.appspot.com',
    iosBundleId: 'com.example.famousRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-nALvU6tUyAnEtdQ--7hQ6kLaW5c1xbQ',
    appId: '1:454995657689:ios:669032e1df023472f48fc8',
    messagingSenderId: '454995657689',
    projectId: 'restaurant-6652e',
    databaseURL: 'https://restaurant-6652e-default-rtdb.firebaseio.com',
    storageBucket: 'restaurant-6652e.appspot.com',
    iosBundleId: 'com.example.famousRestaurant.RunnerTests',
  );
}
